//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phones.DataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class Contacts
    {
        public System.Guid ID_Contact { get; set; }
        public string contactName { get; set; }
        public string phoneNum { get; set; }
        public bool IsDeleted { get; set; }
    }
}
